apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-node-deployment
  labels:
    app: myapp-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-node
  template:
    metadata:
      labels:
        app: myapp-node
    spec:
      containers:
        - name: myapp-node
          image: charlieorch/capstone-app:node
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: node-port
              containerPort: 3001
          livenessProbe:
            httpGet:
              path: /
              port: node-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: node-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
