apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-ingress-service
  labels:
    name: myapp-node
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: myapp-node-clusterip-service
                port:
                  number: 80
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: nodeapp-ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             backend:
#               serviceName: myapp-node-clusterip-service
#               servicePort: 3001
