apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nodeapp-ingress-service
  labels:
    name: myapp-node
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: myapp-node-clusterip-service
              servicePort: 3001
